version: "3.3"
services:
  mysql:
    image: jsurf/rpi-mariadb
    networks:
      - backend
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: hydrodb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: dbpass
  phpmyadmin:
    image: ebspace/armhf-phpmyadmin:latest
    depends_on:
    - mysql
    external_links:
    - mysql:mysql
    ports:
    - "8000:80"
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: dbpass
      PMA_HOST: mysql
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend: